_empty = [];

_generalstore = 
	[
	"Fuelline",
	"kanister", 
	"kleinesreparaturkit", 
	"Bread", 
	"boar",
	"medikit",
	"handy",
	"lighter",
	"fishingpole",
	"Stone",
	"ziptie", 
	"Binocular",
	"GPS"
	];

_fs = 
	[
	"Fuelline", 
	"kanister", 
	"kleinesreparaturkit", 
	"reparaturkit"
	];

_is = 
	[
	"perch", 
	"trout", 
	"walleye", 
	"bass", 
	"Bread",
	"medikit",
	"handy",
	"lighter",
	"fishingpole"
	];
	
_pub = 
	[
	"beer", 
	"beer2", 
	"vodka", 
	"smirnoff",
	"wiskey",
	"wine", 
	"wine2"
	];
	
_gs = 
	[
	"Stone",
	"glock17_EP1",
	"Rnd_9x19_glock17", 
	"M9",
	"Rnd_9x19_M9",
	"Colt1911",
	"Rnd_45ACP_1911",
	"revolver_EP1",
	"Rnd_45ACP",
	"CZ_550",
	"x_22_LR_17_HMR",
	"LeeEnfield",
	"x_303", 
	"Saiga_ill",
	"Rnd_B_Saiga12_Pellets",
	"M16A2",
	"Rnd_20_Stanag", 
	"FN_FAL", 
	"Rnd_762x51_FNFAL"
	];
	
_es = 
	[
	"handy",
	"Binocular",
	"GPS", 
	"lockpick",
	"Fuelline",
	"Stone"
	];
	

_cp = 
	[
	"SearchLight_US_EP1",
	"roadblock",
	"bargate",
	"BigbagfenceCorner",
	"bigbagfence",
	"bigbagfenceRound",
	"bunkersmall",
	"danger",
	"roadcone",
	"barrack",
	"Sign_Checkpoint_US_EP1",
	"Land_CamoNetVar_NATO_EP1",
	"Land_ladderEP1",
	"Land_Campfire_burning"
	
	
	];
	
_cs = 
	[
	"Old_bike_TK_CIV_EP1",
	"MMT_Civ",
	"Old_moto_TK_Civ_EP1",
	"TT650_TK_CIV_EP1",
	"TT650_Civ",
	"TT650_Ins",
	"M1030",
	"ATV_CZ_EP1",
	"Skoda",
	"SkodaBlue",
	"SkodaRed",
	"SkodaGreen",
	"Volha_1_TK_CIV_EP1",
	"Volha_2_TK_CIV_EP1",
	"VolhaLimo_TK_CIV_EP1",
	"Lada1_TK_CIV_EP1",
	"Lada2_TK_CIV_EP1",
	"VWGolf",
	"car_hatchback",
	"Car_Sedan",
	"Lada1",
	"Lada2",
	"S1203_TK_CIV_EP1",
	"LandRover_TK_CIV_EP1",
	"LandRover_CZ_EP1",
	"hilux1_civil_1_open",
	"hilux1_civil_2_covered",
	"hilux1_civil_3_open_EP1",
	"hilux1_civil_3_open",
	"datsun1_civil_1_open",
	"datsun1_civil_2_covered",
	"datsun1_civil_3_open"
	];

_ts = 
	[
	"Tractor",
	"tractorOld",
	"Ikarus",
	"Ikarus_TK_CIV_EP1",
	"Ural_TK_CIV_EP1",
	"UralCivil",
	"UralCivil2",
	"V3S_Open_TK_CIV_EP1",
	"V3S_Civ"
	];

_as = 
	[
	"AH6X_EP1",
	"MH6J_EP1",
	"Mi17_Civilian",
	"BAF_Merlin_HC3_D",
	"MV22",
	"An2_1_TK_CIV_EP1",
	"An2_2_TK_CIV_EP1",
	"C130J"
	];

_as_1 = 
	[
	"AH6X_EP1",
	"MH6J_EP1",
	"Mi17_Civilian",
	"BAF_Merlin_HC3_D",
	"MV22",
	"An2_1_TK_CIV_EP1",
	"An2_2_TK_CIV_EP1",
	"C130J"
	];

_td = 
	[
	"medikit"
	];

_ms = 
	[
	"Shovel",
	"Pickaxe",
	"JackHammer"
	];

_rs = 
	[
	"Diamond rock",
	"Platinum",
	"Gold",
	"Silver",
	"Rubies",
	"iron",
	"copper",
	"steel",
	"sand",
	"glass"
	];

_gds = 
	[
	"Diamondring",
	"EDiamondring",
	"Platinumring",
	"EPlatinumring"
	];

_os = 
	[
	"OilBarrel"
	];

_gangshop_buy =
	[
	"GPS_ill",
	"Binocular_ill",
	"NVGoggles_ill",
	"kleinesreparaturkit",
	"reparaturkit",
	"lockpick",
	"lighter",
	"Fuelline",
	"kanister",
	"medikit",
	"revolver_ill",
	"Rnd_45ACP",
	"Makarov",
	"Rnd_9x18_Makarov",
	"Colt_ill",
	"Rnd_45ACP_1911",
	"UZI_EP1",
	"Rnd_9x19_UZI",
	"LeeEnfield_ILL",
	"x_303",
	"HandGrenade",
	"Stone",
	"AK_47_M",
	"Rnd_762x39_AK47",
	"AKS74U",
	"Rnd_545x39_AK",
	"ziptie"
	];

_db1 = 
	[
	"marijuana",
	"cocaine",
	"lsd"
	];

_db2 = 
	[
	"cocaine",
	"lsd"
	];

_db3 = 
	[
	"heroin",
	"marijuana"
	];

_dsc = 
	[
	"cocaine"
	];

_dsm = 
	[
	"marijuana"
	];

_dsl = 
	[
	"lsd"
	];

_dsh = 
	[
	"heroin"
	];

_cv = 
	[
	"Old_bike_TK_INS_EP1",
	"MMT_USMC",
	"M1030_US_DES_EP1",
	"ATV_US_EP1",
	"VolhaLimo_TK_CIV_EP1",
	"LadaLM",
	"SUV_UN_EP1_retex",
	"HMMWV_Armored",
	"UAZ_Unarmed_UN_EP1",
	"Ural_UN_EP1",
	"MTVR_DES_EP1",
	"MtvrReammo_DES_EP1",
	"MtvrRefuel_DES_EP1",
	"MtvrRepair_DES_EP1"
	];

_ca = 
	[
	"An2_TK_Cop",
	"RQ1Predator",
	"MQ9PredatorB_US_EP1",
	"MV22",
	"C130J_US_EP1_cop",
	"AV8B",
	"AV8B2",
	"AV8B_AS",	
	"A10_US_EP1"
	];

_sv = 
	[
	"HMMWV",
	"HMMWV_DES_EP1",
	"HMMWV_M1035_DES_EP1",
	"HMMWV_Terminal_EP1",
	"HMMWV_Armored",
	"HMMWV_M998A2_SOV_DES_EP1",
	"HMMWV_MK19_DES_EP1",
	"HMMWV_M998_crows_M2_DES_EP1",
	"HMMWV_M1151_M2_DES_EP1",
	"HMMWV_TOW_DES_EP1",
	"HMMWV_Avenger_DES_EP1",
	"BAF_Jackal2_L2A1_D",
	"BAF_Jackal2_GMG_D",
	"M113Ambul_UN_EP1",
	"M113_UN_EP1",
	"AAV",
	"M1133_MEV_EP1",
	"M1130_CV_EP1",
	"M1126_ICV_M2_EP1",
	"M1126_ICV_MK19_EP1",
	"M1129_MC_EP1",
	"M1135_ATGMV_EP1",
	"M1128_MGS_EP1",
	"M2A2_EP1",
	"M2A3_EP1",
	"M6_EP1",
	"BAF_FV510_D",
	"BAF_FV510_W",
	"M1A1_US_DES_EP1",
	"M1A2_US_TUSK_MG_EP1",	
	"MLRS_DES_EP1",
	"ARTY_30Rnd_105mmHE_M119",
	"ARTY_30Rnd_105mmWP_M119",
	"ARTY_30Rnd_105mmSADARM_M119",
	"Stinger_Pod_US_EP1"
	
	];

_sa = 
	[
	"MH6J_EP1",
	"AH6X_EP1",
	"AH6J_EP1",
	"Mi17_UN_CDF_EP1",
	"UH1H_TK_GUE_EP1",
	"UH60M_MEV_EP1",
	"MH60S",
	"UH60M_EP1",
	"CH_47F_EP1",
	"AW159_Lynx_BAF",
	"AH64D_EP1",
	"AH1Z"
	];

_pmcveh = 
	[
	"BAF_ATV_D",
	"MMT_USMC",
	"M1030",
	"SUV_PMC_BAF",
	"ArmoredSUV_PMC",
	"HMMWV_M1035_DES_EP1",
	"HMMWV_DES_EP1",
	"HMMWV_M1151_M2_CZ_DES_EP1",
	"MTVR_DES_EP1",
	"MtvrReammo_DES_EP1",
	"MtvrRefuel_DES_EP1",
	"MtvrRepair_DES_EP1",
	"BAF_Jackal2_L2A1_D"
	];
	
_pmcair = 
	[
	"MH6J_EP1",
	"Ka60_PMC",
	"UH60M_MEV_EP1",
	"UH60M_EP1",
	"BAF_Merlin_PMC"
	];
_pmcs        =
	[
	"handy",
	"GPS",
	"NVGoggles",
	"Binocular",
	"Binocular_Vector",
	"Laserdesignator",
	"Laserbatteries",
	"ziptie",
	"lockpick",
	"medikit",
	"kleinesreparaturkit",
	"reparaturkit",
	"kanister",
	"supgrade1",
	"supgrade2",
	"supgrade3",
	"supgrade4",
	"supgrade5",
	"nitro",
	"vclammo",
	"gasmask",
	"stun_light",
	"M9_PMC",
	"M9SD_PMC",
	"glock17_PMC",
	"Rnd_9x19_M9",
	"Rnd_9x19_glock17",
	"AA12_PMC",
	"Rnd_B_AA12_74Slug",
	"Rnd_B_AA12_Pellets",
	"Rnd_B_AA12_HE_sup",
	"m16a4",
	"M16A4_GL",
	"M4A1",
	"M4A1_Aim",
	"M4A1_AIM_SD_camo",
	"M4A3_CCO_EP1",
	"M4A3_RCO_GL_EP1",
	"Rnd_20_Stanag",
	"Rnd_556x45_Stanag",
	"FN_FAL",
	"Rnd_762x51_FNFAL",
	"AK_47_M",
	"AK_47_S",
	"Rnd_762x39_AK47",
	"AKS74U",
	"AKS_74_UN_kobra",
	"RPK_74",
	"AK74",
	"AK74GL",
	"AKS_74",
	"AKS74kobra",
	"AKS74kobragl",
	"AKS74pso",
	"Rnd_545x39_AK",
	"Rnd_545x39_AKSD",
	"Rnd_545x39_RPK",
	"MP5A5",
	"Rnd_9x19_MP5",
	"G36A_camo",
	"G36C_camo",
	"G36K_camo",
	"G36_C_SD_camo",
	"Rnd_556x45_G36",
	"Rnd_556x45_G36SD",
	"m8_carbine",
	"m8_SAW",
	"m8_sharpshooter",
	"m8_carbine_pmc",
	"m8_carbineGL",
	"M8_compact",
	"m8_compact_pmc",
	"m8_holo_sd",
	"Rnd_20_Stanag",
	"Rnd_556x45_Stanag",
	"Rnd_556x45_StanagSD",
	"BAF_L85A2_RIS_Holo",
	"BAF_L85A2_UGL_Holo",
	"BAF_L85A2_RIS_ACOG",
	"BAF_L85A2_UGL_ACOG",
	"BAF_L85A2_RIS_SUSAT",
	"BAF_L85A2_UGL_SUSAT",
	"BAF_L86A2_ACOG",
	"Rnd_20_Stanag",
	"Rnd_556x45_Stanag",
	"M249_EP1",
	"M249_m145_EP1",
	"Rnd_100_M249",
	"Rnd_200_M249",
	"BAF_L110A1_Aim",
	"Rnd_556x45_L110A1",
	"Mk_48",
	"Mk_48_DES_EP1",
	"BAF_L7A2_GPMG",
	"Rnd_762x51_M240",
	"M24",
	"M24_des_EP1",
	"Rnd_762x51_M24",
	"M110_NVG_EP1",
	"rnd_762x51_B_SCAR",
	"DMR",
	"M14_EP1",
	"Rnd_762x51_DMR",
	"M136",
	"M136_m",	
	"Mk13",
	"Igla",
	"Igla_mag",
	"Rnd_HE_M203",
	"Rnd_Smoke_M203",
	"Rnd_SmokeRed_M203",
	"Rnd_SmokeGreen_M203",
	"Rnd_SmokeYellow_M203",
	"FlareWhite_M203",
	"FlareGreen_M203",
	"FlareRed_M203",
	"FlareYellow_M203",
	"HandGrenade_BAF",
	"SmokeShell",
	"SmokeShellRed",
	"SmokeShellGreen",
	"SmokeShellYellow",
	"SmokeShellPurple",
	"SmokeShellBlue",
	"SmokeShellOrange",
	"PipeBomb",
	"Mine",
	"Tripod_Bag",
	"BAF_GPMG_Minitripod_D_bag",
	"BAF_L2A1_ACOG_tripod_bag",
	"BAF_L2A1_ACOG_minitripod_bag",
	"CZ_Backpack_EP1",
	"CZ_VestPouch_EP1",
	"BAF_AssaultPack_FAC"
	];
	
_copshop =
	[
	"handy",
	"kleinesreparaturkit",
	"reparaturkit",
	"kanister",
	"medikit",
	"weaponbag",
	"Itembag",
	"defuser",
	"vclammo",
	"lockpick",
	"Binocular",
	"Binocular_Vector",
	"NVGoggles",
	"Laserdesignator",
	"Laserbatteries",
	"nitro",
	"supgrade1",
	"supgrade2",
	"supgrade3",
	"supgrade4",
	"supgrade5",
	"gasmask",
	"stun_light",
	"stun_full",
	"CZ_Backpack_EP1",
	"CZ_VestPouch_EP1",
	"USBasicBag",
	"US_Assault_Pack_EP1",
	"US_Backpack_EP1",
	"US_Patrol_Pack_EP1",
	"Tripod_Bag",
	"M2HD_mini_TriPod_US_Bag_EP1",
	"M2StaticMG_US_Bag_EP1",	
	"MK19_TriPod_US_Bag_EP1",
	"M252_US_Bag_EP1",
	"TOW_TriPod_US_Bag_EP1"
	];

_copshop_patrol =
	[
	"M9",
	"Rnd_9x19_M9",
	"Rnd_9x19_M9SD",
	"M1014",
	"Rnd_B_Beneli_74Slug",
	"Rnd_B_Beneli_Pellets",
	"MP5A5",
	"Rnd_9x19_MP5",
	"FN_FAL",
	"Rnd_762x51_FNFAL",
	"M4A1",
	"M16A2",
	"M16A2GL",
	"m16a4",
	"M16A4_GL",
	"Rnd_20_Stanag",
	"SmokeShell",
	"SmokeShellRed",
	"SmokeShellGreen",
	"SmokeShellYellow",
	"SmokeShellPurple",
	"SmokeShellBlue",
	"SmokeShellOrange",
	"Rnd_Smoke_M203",
	"Rnd_SmokeRed_M203",
	"Rnd_SmokeGreen_M203",
	"Rnd_SmokeYellow_M203",
	"FlareWhite_M203",
	"FlareGreen_M203",
	"FlareRed_M203",
	"FlareYellow_M203"
	];

_copshop_response =
	[
	"glock17_EP1",
	"Rnd_9x19_glock17",
	"M4A1_Aim",
	"M4A1_HWS_GL",
	"M4A1_RCO_GL",
	"m16a4_acg",
	"M16A4_ACG_GL",
	"SCAR_L_STD_HOLO",
	"SCAR_L_STD_Mk4CQT",
	"SCAR_L_CQC",
	"SCAR_L_CQC_Holo",
	"SCAR_L_CQC_EGLM_Holo",
	"SCAR_L_STD_EGLM_RCO",
	"Rnd_556x45_Stanag",
	"SCAR_L_CQC_CCO_SD",
	"Rnd_556x45_StanagSD",
	"Sa58V_CCO_EP1",
	"Sa58V_RCO_EP1",
	"Rnd_762x39_SA58",
	"MP5SD",
	"Rnd_9x19_MP5SD",
	"G36a",
	"G36C",
	"G36K",
	"G36_C_SD_eotech",
	"Rnd_556x45_G36",
	"Rnd_556x45_G36SD",
	"M4SPR",
	"Rnd_20_Stanag",
	"Mk13",
	"Rnd_HE_M203",
	"Rnd_Smoke_M203",
	"Rnd_SmokeRed_M203",
	"Rnd_SmokeGreen_M203",
	"Rnd_SmokeYellow_M203",
	"FlareWhite_M203",
	"FlareGreen_M203",
	"FlareRed_M203",
	"FlareYellow_M203",
	"SmokeShell",
	"SmokeShellRed",
	"SmokeShellGreen",
	"SmokeShellYellow",
	"SmokeShellPurple",
	"SmokeShellBlue",
	"SmokeShellOrange",
	"HandGrenade_West"
	];

_copshop_sobr =
	[
	"M9SD",
	"Rnd_9x19_M9SD",
	"G36A_camo",
	"G36C_camo",
	"G36K_camo",
	"G36_C_SD_camo",
	"Rnd_556x45_G36",
	"Rnd_556x45_G36SD",
	"Rnd_556x45_BetaCMag",
	"BAF_L85A2_RIS_Holo",
	"BAF_L85A2_UGL_Holo",
	"BAF_L85A2_RIS_ACOG",
	"BAF_L85A2_UGL_ACOG",
	"BAF_L85A2_RIS_SUSAT",
	"BAF_L85A2_UGL_SUSAT",
	"BAF_L86A2_ACOG",
	"Rnd_556x45_Stanag",
	"M4A1_Aim_camo",
	"M4A1_HWS_GL_camo",
	"M4A3_RCO_GL_EP1",
	"M4A3_CCO_EP1",
	"Rnd_556x45_Stanag",
	"M4A1_AIM_SD_camo",
	"M4A1_HWS_GL_SD_Camo",
	"Rnd_556x45_StanagSD",
	"SCAR_H_CQC_CCO",
	"SCAR_H_STD_EGLM_Spect",
	"SCAR_H_LNG_Sniper",
	"rnd_762x51_B_SCAR",
	"SCAR_H_CQC_CCO_SD",
	"Rnd_762x51_SB_SCAR",
	"M24",
	"M24_des_EP1",
	"Rnd_762x51_M24",
	"M240",
	"m240_scoped_EP1",
	"Rnd_762x51_M240",
	"Mk_48",
	"Mk_48_DES_EP1",
	"M60A4_EP1",
	"M249_200",
	"M249_EP1",
	"Rnd_100_M249",
	"M249_m145_EP1",
	"Rnd_100_M249",
	"DMR",
	"M14_EP1",
	"Rnd_762x51_DMR",
	"BAF_LRR_scoped",
	"Rnd_86x70_L115A1",
	"MAAWS",
	"MAAWS_HEAT",
	"MAAWS_HEDP",
	"SMAW",
	"SMAW_HEAA",
	"SMAW_HEDP",
	"M47Launcher_EP1",
	"Dragon_mag",	
	"M32",
	"Rnd_HE",
	"Rnd_Smoke",
	"Rnd_SmokeRed",
	"Rnd_SmokeGreen",
	"Rnd_SmokeYellow",
	"Rnd_FlareWhite",
	"Rnd_FlareGreen",
	"Rnd_FlareRed",
	"Rnd_FlareYellow",
	"Rnd_HE_M203",
	"Rnd_Smoke_M203",
	"Rnd_SmokeRed_M203",
	"Rnd_SmokeGreen_M203",
	"Rnd_SmokeYellow_M203",
	"FlareWhite_M203",
	"FlareGreen_M203",
	"FlareRed_M203",
	"FlareYellow_M203",
	"SmokeShell",
	"SmokeShellRed",
	"SmokeShellGreen",
	"SmokeShellYellow",
	"SmokeShellPurple",
	"SmokeShellBlue",
	"SmokeShellOrange",
	"HandGrenade_West",
	"PipeBomb",
	"Mine"
	];



_terrorshop_buy = 
	[
	"handy",
	"GPS_ill",
	"Binocular_ill",
	"Binocular_Vector_ill",
	"NVGoggles_ill",
	"lockpick",
	"medikit",
	"kleinesreparaturkit",
	"reparaturkit",
	"kanister",
	"supgrade1",
	"supgrade2",
	"supgrade3",
	"supgrade4",
	"supgrade5",
	"nitro",
	"vclammo",
	"Mammo_HE",
	"Mammo_WP",
	"Mammo_IL",
	"gasmask",
	"stun_light_ter",
	"selbstmordbombe",
	"fernzuenderbombe",
	"zeitzuenderbombe",
	"aktivierungsbombe",
	"geschwindigkeitsbombe",
	"fernzuender",
	"Colt_ill",
	"Rnd_45ACP_1911",
	"revolver_ill",
	"revolver_gold_EP1",
	"Rnd_45ACP",
	"Makarov",
	"MakarovSD",
	"Rnd_9x18_Makarov",
	"Rnd_9x18_MakarovSD",
	"UZI_EP1",
	"UZI_SD_EP1",
	"Rnd_9x19_UZI",
	"Rnd_9x19_UZI_SD",
	"Sa61_EP1",
	"Rnd10_765x17_Ball",
	"Rnd20_765x17_Ball",
	"Saiga_ill",
	"Rnd_B_Saiga12_74Slug",
	"Rnd_B_Saiga12_Pellets",
	"LeeEnfield_ILL",
	"x_303",
	"FN_FAL_ILL",
	"Rnd_762x51_FNFAL",
	"AK_47_M",
	"AK_47_S",
	"AKS_GOLD",
	"Rnd_762x39_AK47",
	"Sa58P_EP1",
	"Sa58V_EP1",
	"Sa58V_CCO_EP1",
	"Sa58V_RCO_EP1",
	"Rnd_762x39_SA58",
	"AKS74U",
	"AKS_74_UN_kobra",
	"RPK_74",
	"AK74",
	"AK74GL",
	"AKS_74",
	"AKS74kobra",
	"AKS74kobragl",
	"AKS74pso",
	"Rnd_545x39_AK",
	"Rnd_545x39_AKSD",
	"Rnd_545x39_RPK",
	"PK",
	"Rnd_762x54_PK",
	"SVD",
	"Rnd_762x54_SVD",
	"CZ_550_ill",
	"x_22_LR_17_HMR",
	"RPG7V",
	"PG7V",
	"PG7VR",
	"PG7VL",
	"OG7",
	"HandGrenade_East",
	"Stone",
	"SmokeShell_ill",
	"M79",
	"Rnd_HE_M203",
	"Rnd_HE_GP25",
	"FlareWhite_GP25",
	"FlareGreen_GP25",
	"FlareRed_GP25",
	"FlareYellow_GP25",
	"Rnd_SMOKE_GP25",
	"Rnd_SmokeRed_GP25",
	"Rnd_SmokeGreen_GP25",
	"Rnd_SmokeYellow_GP25",
	"MineE",
	"Garbage IED Small",
	"Garbage IED Large",
	"Ground IED Small",
	"Ground IED Large",
	"TK_ALICE_Pack_EP1",
	"TK_Assault_Pack_EP1",
	"TK_RPG_Backpack_EP1",
	"Tripod_Bag",
	"DSHkM_Mini_TriPod_TK_GUE_Bag_EP1",
	"DSHKM_TK_GUE_Bag_EP1",
	"2b14_82mm_TK_INS_Bag_EP1",
	"ziptie"
	];

_smgrw =
	[
	"handy",
	"GPS_ill",
	"Binocular_ill",
	"NVGoggles_ill",
	"kleinesreparaturkit",
	"reparaturkit",
	"lockpick",
	"lighter",
	"Fuelline",
	"kanister",
	"medikit",
	"stun_light_ill",
	"M9_ill",
	"Rnd_9x19_M9",
	"Colt_ill",
	"Rnd_45ACP_1911",
	"revolver_ill",
	"revolver_gold_EP1",
	"Rnd_45ACP",
	"Makarov",
	"MakarovSD",
	"Rnd_9x18_Makarov",
	"Rnd_9x18_MakarovSD",
	"UZI_EP1",
	"UZI_SD_EP1",
	"Rnd_9x19_UZI",
	"Rnd_9x19_UZI_SD",
	"Sa61_EP1",
	"Rnd10_765x17_Ball",
	"Rnd20_765x17_Ball",
	"Rnd_9x19_M9",
	"Saiga_ill",
	"Rnd_B_Saiga12_74Slug",
	"Rnd_B_Saiga12_Pellets",
	"M16A2_ill",
	"M4A1_ill",
	"G36C_ill",
	"Rnd_556x45_Stanag",
	"Rnd_556x45_G36",
	"AK_47_M",
	"AK_47_S",
	"AKS_GOLD",
	"Rnd_762x39_AK47",
	"AKS74U",
	"Rnd_545x39_AK",
	"LeeEnfield_ILL",
	"x_303",
	"FN_FAL_ILL",
	"Rnd_762x51_FNFAL",
	"ziptie"
	];

_smgrveh =
	[
	"Lada1_ill",
	"Lada2_ill", 
	"VolhaLimo_TK_CIV_ill",
	"Car_Sedan_ill",
	"VWGolf_ill",
	"LandRover_TK_CIV_ill",
	"hilux1_civil_3_open_ill", 
	"Ural_TK_CIV_ill",
	"V3S_Open_TK_CIV_ill", 
	"Offroad_DSHKM_INS", 
	"Pickup_PK_INS"
	];

_fm = 
	[
	"perch",
	"trout",
	"walleye",
	"bass"
	];

_bm = 
	[
	"rabbit",
	"chicken",
	"cow",
	"sheep"
	];

_bm1 = 
	[
	"boar",
	"goat",
	"dog"
	];
_hash = 
	[
	"marijuana",
	"cocaine",
	"lsd"
	];
_igs = 
	[
	"GPS_ill",
	"Binocular_ill",
	"Binocular_Vector_ill",
	"NVGoggles_ill",
	"Colt_ill",
	"Rnd_45ACP_1911",
	"revolver_ill",
	"revolver_gold_EP1",
	"Rnd_45ACP",
	"Makarov",
	"MakarovSD",
	"Rnd_9x18_Makarov",
	"Rnd_9x18_MakarovSD",
	"UZI_EP1",
	"UZI_SD_EP1",
	"Rnd_9x19_UZI",
	"Rnd_9x19_UZI_SD",
	"Sa61_EP1",
	"Rnd10_765x17_Ball",
	"Rnd20_765x17_Ball",
	"Saiga_ill",
	"Rnd_B_Saiga12_74Slug",
	"Rnd_B_Saiga12_Pellets",
	"LeeEnfield_ILL",
	"x_303",
	"FN_FAL_ILL",
	"Rnd_762x51_FNFAL",
	"Sa58P_EP1",
	"Sa58V_EP1",
	"Rnd_762x39_SA58",
	"AK_47_M",
	"AK_47_S",
	"Rnd_762x39_AK47",
	"AKS74U",
	"AKS_74_UN_kobra",
	"RPK_74",
	"AK74",
	"AK74GL",
	"AKS_74",
	"AKS74kobra",
	"AKS74kobragl",
	"AKS74pso",
	"Rnd_545x39_AK",
	"Rnd_545x39_AKSD",
	"Rnd_545x39_RPK",
	"PK",
	"Rnd_762x54_PK",
	"SVD",
	"Rnd_762x54_SVD",
	"CZ_550_ill",
	"x_22_LR_17_HMR",
	"RPG7V",
	"PG7V",
	"PG7VR",
	"PG7VL",
	"OG7",
	"RPG18",
	"RPG18_mag",
	"HandGrenade_East",
	"Stone",
	"SmokeShell_ill",
	"M79",
	"Rnd_HE_M203",
	"Rnd_HE_GP25",
	"FlareWhite_GP25",
	"FlareGreen_GP25",
	"FlareRed_GP25",
	"FlareYellow_GP25",
	"Rnd_SMOKE_GP25",
	"Rnd_SmokeRed_GP25",
	"Rnd_SmokeGreen_GP25",
	"Rnd_SmokeYellow_GP25",
	"MineE",
	"GarbageIEDSmall_PMC",
	"GroundIEDSmall_PMC",
	"GarbageIEDLarge_PMC",
	"GroundIEDLarge_PMC",
	"TimeBomb",
	"PipeBomb",
	"TK_ALICE_Pack_EP1",
	"TK_Assault_Pack_EP1",
	"TK_RPG_Backpack_EP1",
	"Tripod_Bag",
	"DSHkM_Mini_TriPod_TK_GUE_Bag_EP1",
	"DSHKM_TK_GUE_Bag_EP1",
	"KORD_high_TK_Bag_EP1",
	"KORD_TK_Bag_EP1",	
	"AGS_TK_Bag_EP1",
	"SPG9_TK_GUE_Bag_EP1",
	"2b14_82mm_TK_Bag_EP1"
	];
_ihs = 
	[
	"UH1H_TK_EP1",
	"Ka137_PMC",
	"Ka137_MG_PMC",
	"Mi17_TK_EP1"
	];
_isup = 
	[
	"handy",
	"lockpick",
	"medikit",
	"kleinesreparaturkit",
	"reparaturkit",
	"kanister",
	"supgrade1",
	"supgrade2",
	"supgrade3",
	"nitro",
	"vclammo",
	"Mammo_HE",
	"Mammo_WP",
	"Mammo_IL",
	"selbstmordbombe",
	"fernzuenderbombe",
	"zeitzuenderbombe",
	"aktivierungsbombe",
	"geschwindigkeitsbombe",
	"fernzuender",
	"gasmask",
	"stun_light_ter",
	"ziptie"
	];
_bt = 
	[
	"Old_bike_TK_INS_EP1",
	"TT650_TK_EP1",
	"UAZ_Unarmed_TK_CIV_EP1",
	"BAF_Offroad_D",
	"Pickup_PK_TK_GUE_EP1",
	"Offroad_DSHKM_TK_GUE_EP1",
	"LandRover_MG_TK_INS_EP1",
	"UAZ_AGS30_TK_EP1",
	"Offroad_SPG9_TK_GUE_EP1",
	"V3S_Open_TK_EP1",
	"V3S_Refuel_TK_GUE_EP1",
	"V3S_Repair_TK_GUE_EP1",
	"V3S_Reammo_TK_GUE_EP1",
	"V3S_Supply_TK_GUE_EP1",
	"V3S_Salvage_TK_GUE_EP1",
	"V3S_TK_GUE_EP1"
	];

_ihvy = 
	[
	"LandRover_Special_CZ_EP1",
	"BTR40_TK_GUE_EP1",
	"BTR40_MG_TK_GUE_EP1",
	"BRDM2_HQ_Gue",
	"BRDM2_ATGM_TK_EP1",
	"M113Ambul_TK_EP1",
	"M113_TK_EP1",
	"Ural_ZU23_TK_EP1",
	"T34_TK_EP1",
	"T55_TK_EP1",
	"MAZ_543_SCUD_TK_EP1",
	"ZU23_TK_EP1",
	"Igla_AA_pod_TK_EP1"
	];

_iair = 
	[
	"An2_TK_EP1"
	];

_rgs = 
	[
	"GPS_ill",
	"Binocular_ill",
	"Binocular_Vector_ill",
	"NVGoggles_ill",
	"Laserdesignator",
	"Laserbatteries",
	"Colt_ill",
	"Rnd_45ACP_1911",
	"revolver_ill",
	"revolver_gold_EP1",
	"Rnd_45ACP",
	"M9",
	"Rnd_9x19_M9SD",
	"Makarov",	
	"Rnd_9x18_Makarov",
	"UZI_EP1",
	"Rnd_9x19_UZI",
	"Sa61_EP1",
	"Rnd10_765x17_Ball",
	"Rnd20_765x17_Ball",
	"Bizon",
	"Rnd_9x19_Bizon",
	"Saiga12K",
	"Rnd_B_Saiga12_74Slug",
	"Rnd_B_Saiga12_Pellets",
	"LeeEnfield_ILL",
	"x_303",
	"FN_FAL_ILL",
	"Rnd_762x51_FNFAL",
	"AK_47_M",
	"AK_47_S",
	"Rnd_762x39_AK47",
	"Sa58P_EP1",
	"Sa58V_EP1",
	"Rnd_762x39_SA58",
	"AKS74U",
	"AKS_74_UN_kobra",
	"RPK_74",
	"AK74",
	"AK74GL",
	"AKS_74",
	"AKS74kobra",
	"AKS74kobragl",
	"AKS74pso",
	"Rnd_545x39_AK",
	"Rnd_545x39_AKSD",
	"Rnd_545x39_RPK",
	"AK107pso",
	"AK107GLpso",
	"AK_107_kobra",
	"AK_107_GL_kobra",
	"Sa58V_CCO_EP1",
	"Sa58V_RCO_EP1",
	"Rnd_762x39_SA58",
	"PK",
	"Rnd_762x54_PK",
	"SVD",
	"SVD_CAMO",
	"SVD_des_EP1",
	"Rnd_762x54_SVD",
	"M24_des_EP1",
	"Rnd_762x51_M24",
	"CZ_550_ill",
	"x_22_LR_17_HMR",
	"RPG7V",
	"PG7V",
	"PG7VR",
	"PG7VL",
	"OG7",
	"RPG18",
	"RPG18_mag",
	"M79",
	"Rnd_HE_M203",
	"Rnd_HE_GP25",
	"FlareWhite_GP25",
	"FlareGreen_GP25",
	"FlareRed_GP25",
	"FlareYellow_GP25",
	"Rnd_SMOKE_GP25",
	"Rnd_SmokeRed_GP25",
	"Rnd_SmokeGreen_GP25",
	"Rnd_SmokeYellow_GP25",
	"HandGrenade_East",
	"Stone",
	"SmokeShell_ill",
	"MineE",
	"PipeBomb",
	"TK_ALICE_Pack_EP1",
	"TK_Assault_Pack_EP1",
	"TK_RPG_Backpack_EP1",
	"Tripod_Bag",
	"DSHkM_Mini_TriPod_TK_GUE_Bag_EP1",
	"DSHKM_TK_GUE_Bag_EP1",
	"KORD_high_TK_Bag_EP1",
	"KORD_TK_Bag_EP1",
	"2b14_82mm_TK_Bag_EP1"
	];
_rsup = 
	[
	"handy",
	"lockpick",
	"medikit",
	"kleinesreparaturkit",
	"reparaturkit",
	"kanister",
	"supgrade1",
	"supgrade2",
	"supgrade3",
	"supgrade4",
	"supgrade5",
	"nitro",
	"vclammo",
	"Mammo_HE",
	"Mammo_WP",
	"Mammo_IL",
	"gasmask",
	"stun_light",
	"stun_full",
	"ziptie"
	];

_rhs = 
	[
	"UH1H_TK_GUE_EP1",
	"CH_47F_BAF",
	"Mi17_medevac_Ins",
	"Mi17_INS",
	"Mi17_rockets_RU",
	"Mi24_D",
	"Mi24_P",
	"Mi24_V",
	"Ka52"
	];
_rlt = 
	[
	"Old_bike_TK_INS_EP1",
	"TT650_TK_EP1",
	"UAZ_INS",
	"BAF_Offroad_W",
	"UAZ_AGS30_INS",
	"UAZ_MG_INS",
	"Kamaz",
	"KamazOpen",
	"KamazReammo",
	"KamazRefuel",
	"KamazRepair"
	];
_rhvy = 
	[
	"UAZ_SPG9_INS",
	"GAZ_Vodnik",
	"GAZ_Vodnik_MedEvac",
	"GAZ_Vodnik_HMG",
	"BTR40_MG_TK_INS_EP1",
	"BTR40_TK_INS_EP1",
	"BRDM2_INS",
	"BRDM2_ATGM_INS",
	"BMP2_INS",
	"BMP2_Ambul_INS",
	"BMP2_HQ_INS",
	"T34_TK_GUE_EP1",
	"T55_TK_GUE_EP1",
	"T72_INS",
	"T90",
	"Ural_ZU23_INS",
	"ZSU_INS",
	"2S6M_Tunguska",
	"GRAD_INS",
	"ARTY_30Rnd_122mmHE_D30",
	"ARTY_30Rnd_122mmWP_D30",
	"ARTY_30Rnd_122mmSADARM_D30",
	"ZU23_Ins",
	"Igla_AA_pod_TK_EP1"
	];

_rair = 
	[
	"Pchela1T",
	"L39_TK_EP1",
	"Su25_Ins",
	"Su27",
	"Su34"
	];

_as_2 = 
	[
	"Offroad_DSHKM_Gue", 
	"Pickup_PK_GUE", 
	"GAZ_Vodnik", 
	"An2_TK_EP1", 
	"UH1H_TK_EP1"
	];

_fs1 =
	[
	"SearchLight_UN",
	"Wire",
	"Hedgehog",
	"BagFenceC",
	"BagFenceE",
	"BagFenceL",
	"BagFenceR",
	"BagFenceS",
	"NBagFenceC",
	"NBagFenceL",
	"NBagFenceR",
	"HBarrC",
	"BunkerS",
	"ZavoraAnim",
	"roadcone",
	"Land_coneLight",
	"Land_arrows_yellow_L",
	"Land_arrows_yellow_R",
	"Land_arrows_desk_R",
	"Land_arrows_desk_L",
	"Land_CncBlock_Stripes",
	"RoadBarrier_light",
	"RoadBarrier_long",
	"Sign_Danger",
	"Sign_Checkpoint_US_EP1",
	"Land_CamoNetVar_NATO",
	"Land_CamoNetB_NATO",
	"Land_CamoNet_NATO"
	];

_fs2 =
	[
	"SearchLight_US",
	"Wire",
	"Hedgehog",
	"BagFenceC",
	"BagFenceE",
	"BagFenceL",
	"BagFenceR",
	"BagFenceS",
	"NBagFenceC",
	"NBagFenceL",
	"NBagFenceR",
	"BunkerS",
	"ZavoraAnim",
	"roadcone",
	"Land_CncBlock_Stripes",
	"RoadBarrier_light",
	"Sign_Danger",
	"Sign_Checkpoint_US_EP1",
	"Land_Campfire_burning"
	];

_fs3 =
	[
	"GuerillaCacheBox_EP1",
	"Fort_Crate_wood",
	"BagFenceC",
	"BagFenceE",
	"BagFenceL",
	"BagFenceR",
	"BagFenceS",
	"NBagFenceC",
	"NBagFenceL",
	"NBagFenceR",
	"ZavoraAnim",
	"Land_CncBlock_Stripes",
	"Sign_Danger"
	];

_fs4 =
	[
	"GuerillaCacheBox_EP1",
	"Wire",
	"Hedgehog",
	"Fort_Crate_wood",
	"BagFenceC",
	"BagFenceE",
	"BagFenceL",
	"BagFenceR",
	"BagFenceS",
	"NBagFenceC",
	"NBagFenceL",
	"NBagFenceR",
	"BunkerS",
	"ZavoraAnim",
	"Land_CncBlock_Stripes",
	"RoadBarrier_light",
	"Sign_Danger",
	"Fort_Barricade_EP1",
	"Fort_Barricade",
	"Land_CamoNetVar_EAST",
	"Land_CamoNetB_EAST",
	"Land_CamoNet_EAST"
	];

_fs5 =
	[
	"SearchLight_UN",
	"GuerillaCacheBox_EP1",
	"Wire",
	"Hedgehog",
	"BagFenceC",
	"BagFenceE",
	"BagFenceL",
	"BagFenceR",
	"BagFenceS",
	"NBagFenceC",
	"NBagFenceL",
	"NBagFenceR",
	"HBarrC",
	"BunkerS",
	"ZavoraAnim",
	"roadcone",
	"Land_coneLight",
	"Land_CncBlock_Stripes",
	"RoadBarrier_light",
	"RoadBarrier_long",
	"Sign_Danger",
	"Sign_Checkpoint_TK_EP1",
	"Land_CamoNetVar_EAST",
	"Land_CamoNetB_EAST",
	"Land_CamoNet_EAST"
	];

_fs6 =
	[
	"GuerillaCacheBox_EP1",
	"Wire",
	"Hedgehog",
	"Fort_Crate_wood",
	"BagFenceC",
	"BagFenceE",
	"BagFenceL",
	"BagFenceR",
	"BagFenceS",
	"NBagFenceC",
	"NBagFenceL",
	"NBagFenceR",
	"HBarrC",
	"BunkerS",
	"ZavoraAnim",
	"roadcone",
	"Land_CncBlock_Stripes",
	"RoadBarrier_light",
	"Sign_Danger",
	"Fort_Barricade_EP1",
	"Fort_Barricade",
	"Land_CamoNetVar_EAST",
	"Land_CamoNetB_EAST",
	"Land_CamoNet_EAST"
	];
	
_fsvip =
	[
	"GuerillaCacheBox_EP1_vip"
	];

_hp =
	[
	"S1203_ambulance_EP1",
	"HMMWV_Ambulance_CZ_DES_EP1"
	];

_russ =
	[
	"GPS_ill",
	"Binocular_ill",
	"NVGoggles_ill",
	"lockpick",
	"lighter",
	"handy",
	"medikit",
	"stun_light_ill",
	"M9_ill",
	"Rnd_9x19_M9",
	"Colt_ill",
	"Rnd_45ACP_1911",
	"revolver_ill",
	"revolver_gold_EP1",
	"Rnd_45ACP",
	"Makarov",
	"MakarovSD",
	"Rnd_9x18_Makarov",
	"Rnd_9x18_MakarovSD",
	"UZI_EP1",
	"UZI_SD_EP1",
	"Rnd_9x19_UZI",
	"Rnd_9x19_UZI_SD",
	"Sa61_EP1",
	"Rnd10_765x17_Ball",
	"Rnd20_765x17_Ball",
	"Saiga_ill",
	"Rnd_B_Saiga12_74Slug",
	"Rnd_B_Saiga12_Pellets",
	"M16A2_ill",
	"M4A1_ill",
	"G36C_ill",
	"Rnd_20_Stanag",
	"Rnd_556x45_Stanag",
	"Rnd_556x45_G36",
	"AK_47_M",
	"AK_47_S",
	"AKS_GOLD",
	"Rnd_762x39_AK47",
	"AKS74U",
	"Rnd_545x39_AK",
	"LeeEnfield_ILL",
	"x_303",
	"FN_FAL_ILL",
	"Rnd_762x51_FNFAL",
	"RPK_74_ill",
	"AK74_ill",
	"AK74GL_ill",
	"AKS_74",
	"AKS74kobragl_ill",
	"AKS74pso_ill",
	"Rnd_545x39_AK",
	"Rnd_545x39_AKSD",	
	"Rnd_545x39_RPK",
	"PK_ill",
	"Rnd_762x54_PK",
	"SVD_ill",
	"Rnd_762x54_SVD"
	];
	
_bank = [
	"bankversicherung"
	];
_cdvs = 
	[
	"SUV_TK_EP1_sup",
	"SUV_TK_CIV_sup",
	"Ural_TK_CIV_EP1_sup",
	"UralReammo_TK_EP1_sup",
	"UralRefuel_TK_EP1_sup",
	"UralRepair_TK_EP1_sup",
	"MTVR_DES_EP1_sup",
	"LandRover_CZ_EP1_sup",
	"hilux1_civil_1_open_sup"
	];
	
_cdws =
	[	
	"GPS_sup",
	"NVGoggles_sup",
	"Binocular_sup",
	"nitro_sup",
	"supgrade1_sup",
	"supgrade2_sup",
	"supgrade5_sup",
	"defuser_sup",
	"lockpick_sup",
	"medikit_sup",
	"kanister_sup", 
	"ziptie_sup",
	"reparaturkit_sup",
	"vclammo",
	"UZI_SD_EP1_sup",
	"Rnd_9x19_UZI_SD_sup",
	"M9SD_sup",
	"Rnd_9x19_M9SD_sup",
	"Colt1911_sup",
	"Rnd_45ACP_1911_sup",
	"glock17_sup",
	"Rnd_9x19_glock17_sup",
	"m8_compact_pmc_sup",
	"m8_carbine_sup",
	"m8_holo_sd_sup", 		
	"Rnd_556x45_G36_sup",
	"Rnd_556x45_G36SD_sup",
	"M16A2_sup",
	"M4A1_sup",
	"M4A1_Aim_sup",
	"M4A1_AIM_SD_camo_sup",
	"Rnd_556x45_Stanag_sup",
	"Rnd_556x45_StanagSD_sup",
	"MP5A5_sup",
	"MP5SD_sup",
	"Rnd_9x19_MP5",
	"Rnd_9x19_MP5SD",
	"revolver_gold_EP1_sup",
	"Rnd_45ACP_sup",
	"CZ_550_sup",
	"x_22_LR_17_HMR_sup",
	"AKS74kobra_sup",
	"AKS74U_sup",
	"Rnd_545x39_AK_sup",
	"AKS_GOLD_sup",
	"AK_47_M_sup",
	"AK_47_S_sup",
	"Rnd_762x39_AK47",
	"SmokeShellYellow",
	"SmokeShellPurple",
	"SmokeShellBlue"
	];
	
_cdas =
	[
	"Mi17_Civilian_sup",
	"MV22_sup",
	"BAF_Merlin_HC3_sup"
	];

_cpdvs = 
	[
	"SUV_TK_EP1_sup",
	"HMMWV_DES_EP1_sup",
	"Ural_TK_CIV_EP1_sup",
	"UralReammo_TK_EP1_sup",
	"UralRefuel_TK_EP1_sup",
	"UralRepair_TK_EP1_sup",
	"MTVR_DES_EP1_sup",
	"SUV_UN_EP1_retex_sup",
	"LandRover_CZ_EP1_sup",
	"hilux1_civil_1_open_sup",
	"HMMWV_Avenger_DES_EP1_sup",
	"BMP2_UN_EP1_sup",
	"LAV25_sup",
	"LAV25_HQ_sup",
	"M1133_MEV_EP1_sup",
	"M1135_ATGMV_EP1_sup",
	"HMMWV_M998A2_SOV_DES_EP1_sup"
	];
	
_cpdws =
	[
	"GPS_sup",
	"NVGoggles_sup",
	"Binocular_sup",
	"nitro_sup",
	"supgrade1_sup",
	"supgrade2_sup",
	"supgrade5_sup",
	"defuser_sup",
	"lockpick_sup",
	"medikit_sup",
	"kanister_sup",
	"ziptie_sup",
	"reparaturkit_sup",
	"vclammo",
	"UZI_SD_EP1_sup",
	"Rnd_9x19_UZI_SD_sup",
	"M9SD_sup",
	"Rnd_9x19_M9SD_sup",
	"Colt1911_sup",
	"Rnd_45ACP_1911_sup",
	"glock17_sup",
	"Rnd_9x19_glock17_sup",
	"Stinger_sup",
	"Stinger_mag_sup",
	"Javelin_vip",
	"Javelin",
	"M47Launcher_EP1_sup",
	"Dragon_mag_sup",
	"M4A1_HWS_GL_SD_Camo_sup",
	"M4A1_AIM_SD_camo_sup",
	"Rnd_556x45_StanagSD_sup",
	"AA12_PMC_sup",
	"Rnd_B_AA12_HE_sup",
	"Rnd_B_AA12_74Slug_sup",
	"Rnd_B_AA12_Pellets_sup",
	"SCAR_H_LNG_Sniper_SD_sup",
	"Rnd_762x51_SB_SCAR_sup",
	"m8_sharpshooter_sup",
	"m8_SAW_sup",
	"m8_compact_pmc_sup",
	"m8_carbine_sup",
	"m8_holo_sd_sup",	
	"Rnd_556x45_G36_sup",
	"Rnd_556x45_G36SD_sup",
	"Rnd_556x45_G36_sup",
	"MG36",
	"MG36_camo",
	"Rnd_556x45_BetaCMag_sup",
	"M24_sup",
	"M24_des_EP1_sup",
	"M40A3_sup",
	"Rnd_762x51_M24_sup",
	"M4SPR_sup",
	"Rnd_556x45_Stanag_sup",
	"M110_NVG_EP1_sup",
	"rnd_762x51_B_SCAR_sup",
	"BAF_AS50_scoped_sup",
	"5Rnd_127x99_as50_sup",
	"DMR_sup",
	"Rnd_762x51_DMR_sup",
	"BAF_L110A1_Aim",
	"Rnd_556x45_L110A1",
	"BAF_L7A2_GPMG",
	"Rnd_762x51_M240",
	"Rnd_HE_M203",
	"Rnd_Smoke_M203",
	"Rnd_SmokeRed_M203",
	"Rnd_SmokeGreen_M203",
	"Rnd_SmokeYellow_M203",
	"FlareWhite_M203",
	"SmokeShellYellow",
	"SmokeShellPurple",
	"SmokeShellBlue",
	"PipeBomb_sup"
	];
	
_cpdas =
	[
	"AH6J_EP1_sup",
	"UH1Y_sup",
	"AW159_Lynx_BAF_sup",
	"AH64D_EP1_sup",
	"BAF_Merlin_HC3_sup",
	"F35B_sup",
	"F35B_sup2"
	];

_idvs = 
	[
	"SUV_TK_EP1_sup",
	"Ural_TK_CIV_EP1_sup",
	"UralReammo_TK_EP1_sup",
	"UralRefuel_TK_EP1_sup",
	"UralRepair_TK_EP1_sup",
	"GAZ_Vodnik_HMG_sup",
	"MTVR_DES_EP1_sup",
	"LandRover_CZ_EP1_sup",
	"hilux1_civil_1_open_sup",
	"BTR60_TK_EP1_sup",
	"BMP2_TK_EP1_sup",
	"Offroad_DSHKM_TK_GUE_EP1_sup",
	"Offroad_SPG9_TK_GUE_EP1_sup",
	"Pickup_PK_TK_GUE_EP1_sup",
	"UAZ_AGS30_INS_sup",
	"UAZ_MG_INS_sup",
	"Ural_ZU23_INS_sup",
	"UAZ_SPG9_INS_sup"
	];
	
_idws =
	[
	"GPS_sup",
	"NVGoggles_sup",
	"Binocular_sup",
	"Laserdesignator",
	"Laserbatteries",
	"nitro_sup",
	"supgrade1_sup",
	"supgrade2_sup",
	"supgrade5_sup",
	"defuser_sup",
	"lockpick_sup",
	"medikit_sup",
	"kanister_sup",
	"ziptie_sup",
	"reparaturkit_sup",
	"vclammo",
	"UZI_SD_EP1_sup",
	"Rnd_9x19_UZI_SD_sup",
	"M9SD_sup",
	"Rnd_9x19_M9SD_sup",
	"Colt1911_sup",
	"Rnd_45ACP_1911_sup",
	"glock17_sup",
	"Rnd_9x19_glock17_sup",
	"SVD_sup",
	"SVD_CAMO_sup",
	"Rnd_762x54_SVD",
	"VSS_Vintorez_sup",
	"Rnd_9x39_10_VSS",
	"Rnd_9x39_20_VSS",
	"RPK_74_sup",
	"Rnd_545x39_RPK",
	"revolver_gold_EP1_sup",
	"Rnd_45ACP_sup",
	"AKS74kobra_sup",
	"AKS74pso_sup",
	"AK_107_GL_kobra_sup",
	"AK_107_kobra_sup",
	"Rnd_545x39_AK_sup",
	"M47Launcher_EP1_sup",
	"Dragon_mag_sup",
	"Igla",
	"Igla_mag",
	"M4A1_HWS_GL_SD_Camo_sup",
	"M4A1_AIM_SD_camo_sup",
	"Rnd_556x45_StanagSD_sup",
	"AA12_PMC_sup",
	"Rnd_B_AA12_HE_sup",
	"Rnd_B_AA12_74Slug_sup",
	"Rnd_B_AA12_Pellets_sup",
	"SCAR_H_LNG_Sniper_SD_sup",
	"Rnd_762x51_SB_SCAR_sup",
	"m8_sharpshooter_sup",
	"m8_SAW_sup",
	"m8_compact_pmc_sup",
	"m8_carbine_sup",
	"m8_holo_sd_sup", 		
	"Rnd_556x45_G36_sup",
	"Rnd_556x45_G36SD_sup",
	"Rnd_556x45_G36_sup",
	"MG36",
	"MG36_camo",
	"Rnd_556x45_BetaCMag_sup",
	"M24_sup",
	"M24_des_EP1_sup",
	"M40A3_sup",
	"Rnd_762x51_M24_sup",
	"M4SPR_sup",
	"Rnd_556x45_Stanag_sup",
	"M110_NVG_EP1_sup",
	"rnd_762x51_B_SCAR_sup",
	"BAF_AS50_scoped_sup",
	"5Rnd_127x99_as50_sup",
	"BAF_LRR_scoped",
	"Rnd_86x70_L115A1",
	"DMR_sup",
	"Rnd_762x51_DMR_sup",
	"BAF_L110A1_Aim",
	"Rnd_556x45_L110A1",
	"BAF_L7A2_GPMG",
	"Rnd_762x51_M240",
	"SmokeShellYellow",
	"SmokeShellPurple",
	"SmokeShellBlue",
	"PipeBomb_sup"
	];
	
_idas =
	[	
	"AH6X_EP1_sup",
	"Mi17_medevac_Ins_sup"
	];

_odvs = 
	[
	"SUV_TK_EP1_sup",
	"Ural_TK_CIV_EP1_sup",
	"UralReammo_TK_EP1_sup",
	"UralRefuel_TK_EP1_sup",
	"UralRepair_TK_EP1_sup",
	"GAZ_Vodnik_HMG_sup",
	"MTVR_DES_EP1_sup",
	"LandRover_CZ_EP1_sup",
	"hilux1_civil_1_open_sup",
	"BTR90_sup",
	"BTR90_HQ_sup",
	"BMP2_TK_EP1_sup",
	"BMP3",
	"HMMWV_Avenger_sup",
	"UAZ_MG_CDF_sup",
	"UAZ_AGS30_CDF_sup"
	];
	
_odws =
	[	
	"GPS_sup",
	"NVGoggles_sup",
	"Binocular_sup",
	"nitro_sup",
	"supgrade1_sup",
	"supgrade2_sup",
	"supgrade5_sup",
	"defuser_sup",
	"lockpick_sup",
	"medikit_sup",
	"kanister_sup", 
	"ziptie_sup",
	"reparaturkit_sup",
	"vclammo",
	"UZI_SD_EP1_sup",
	"Rnd_9x19_UZI_SD_sup",
	"M9SD_sup",
	"Rnd_9x19_M9SD_sup",
	"Colt1911_sup",
	"Rnd_45ACP_1911_sup",
	"revolver_gold_EP1_sup",
	"Rnd_45ACP_sup",
	"glock17_sup",
	"Rnd_9x19_glock17_sup",
	"SVD_NSPU_EP1_sup",
	"SVD_des_EP1_sup",
	"SVD_CAMO_sup",
	"SVD_sup",
	"Rnd_762x54_SVD",
	"VSS_Vintorez_sup",
	"Rnd_9x39_10_VSS",
	"Rnd_9x39_20_VSS",
	"AKS_74_NSPU_sup",
	"Sa58V_CCO_EP1_sup",
	"Sa58V_RCO_EP1_sup",
	"Sa58P_EP1_sup",
	"Sa58V_EP1_sup",
	"Rnd_762x39_SA58",
	"KSVK_sup",
	"5Rnd_127x108_KSVK_sup",
	"AK107pso_sup",
	"AK_107_kobra_sup",
	"AKS74U_sup",
	"Rnd_545x39_AK",
	"bizon_silenced_sup",
	"Rnd_9x19_SD_Bizon",
	"Pecheneg_sup",
	"Rnd_762x54_PK",
	"RPK_74_sup",
	"Rnd_545x39_RPK",
	"Igla",
	"Igla_mag",
	"SmokeShellYellow",
	"SmokeShellPurple",
	"SmokeShellBlue",
	"PipeBomb_sup"
	];
	
_odas =
	[
	"Mi17_CDF_sup",
	"Ka52Black_sup",
	"Ka60_PMC_sup",
	"Su25_Ins_sup"
	];
	
_vipshop =
[
	"GPS_vip",
	"NVGoggles_vip",
	"Binocular_vip",
	"Binocular_Vector_vip",
	"lockpick_vip",
	"medikit_vip",
	"kleinesreparaturkit_vip",
	"reparaturkit_vip",
	"vclammo",
	"kanister_vip",
	"supgrade5_vip",
	"nitro_vip",
	"UZI_SD_EP1_vip",
	"Rnd_9x19_UZI_SD_vip",
	"M9SD_vip",
	"Rnd_9x19_M9SD_vip",
	"Colt1911_vip",
	"Rnd_45ACP_1911_vip",
	"glock17_vip",
	"Rnd_9x19_glock17_vip",
	"revolver_gold_EP1_vip",
	"Rnd_45ACP_vip",
	"MakarovSD_vip",
	"Rnd_9x18_MakarovSD_vip",
	"KSVK_vip",
	"5Rnd_127x108_KSVK_vip",
	"AKS_74_NSPU_vip",
	"AKS74GOSHAWK_vip",
	"Rnd_545x39_AK_vip",
	"M4A1_HWS_GL_SD_Camo_vip",
	"M4A1_AIM_SD_camo_vip",
	"BAF_L85A2_RIS_CWS_vip",
	"Rnd_556x45_Stanag_vip",
	"Rnd_556x45_StanagSD_vip",
	"M110_NVG_EP1_vip",
	"M110_TWS_EP1_vip",
	"rnd_762x51_B_SCAR_vip",
	"SCAR_H_STD_TWS_SD_vip",
	"Rnd_762x51_SB_SCAR_vip",
	"DMR_vip",
	"Rnd_762x51_DMR_vip",
	"bizon_silenced_vip",
	"Rnd_9x19_SD_Bizon",
	"M107_vip",
	"m107_TWS_EP1_vip",
	"10Rnd_127x99_m107_vip",
	"BAF_AS50_scoped_vip",
	"PMC_AS50_scoped_vip",
	"BAF_AS50_TWS_vip",
	"PMC_AS50_TWS_vip",
	"5Rnd_127x99_as50_sup",
	"10Rnd_127x99_m107_vip",
	"m8_tws_vip",
	"SCAR_L_STD_EGLM_TWS_vip",
	"Rnd_556x45_BetaCMag_sup",
	"m8_tws_sd_vip",	
	"Rnd_556x45_StanagSD_vip",
	"FN_FAL_ANPVS4_vip",
	"Rnd_762x51_FNFAL",
	"M249_TWS_vip",
	"Rnd_200_M249_vip",
	"MetisLauncher_vip",
	"AT13_mag",
	"Javelin_vip",
	"Javelin",
	"Stinger_sup",
	"Stinger_mag_sup",
	"Strela_vip",
	"Strela_mag",
	"Rnd_HE_M203_vip"
];

_vipcarshop =
[
	"SUV_TK_EP1_vip",
	"Ural_TK_CIV_EP1_vip",
	"UralRefuel_TK_EP1_vip",
	"MTVR_DES_EP1_vip",
	"hilux1_civil_1_open_vip",
	"AH6X_EP1_vip",
	"HMMWV_M1035_DES_EP1_vip"
];

_newsstationcar =
[
	"SUV_TK_EP1_news"
	
	
	
];

_newsstationair =
[
	"MH6J_EP1_news"
		
];

INV_ItemShops = [
[vipshop,["","VIP supporter Shop"],vipshopbox,dummyobj,_vipshop,_vipshop,true,{true}],
[vipcarshop,["","VIP supporter Vehicle Shop"],dummyobj,vipshopcarspawn,_vipcarshop,_vipcarshop,true,{true}],
[vipshop_1,["","VIP supporter Shop"],vipshopbox_1,dummyobj,_vipshop,_vipshop,true,{true}],
[vipcarshop_1,["","VIP supporter Vehicle Shop"],dummyobj,vipshopcarspawn_1,_vipcarshop,_vipcarshop,true,{true}],
[newscarshop,["","News Reporter Car Shop"],dummyobj,newscarspawn,_newsstationcar,_newsstationcar,true,{true}],
[newsairshop,["","News Reporter Air Shop"],dummyobj,newsairspawn,_newsstationair,_newsstationair,true,{true}],
[fuelshop1,["Gas pump","Gas n Porn"],dummyobj,dummyobj,_fs,_fs,true,{true}],
[fuelshop2,["Gas pump","Gas N Pit"],dummyobj,dummyobj,_fs,_fs,true,{true}],
[fuelshop3,["Gas pump","Gas N Chips"],dummyobj,dummyobj,_fs,_fs,true,{true}],
[fuelshop4,["Gas pump","Gas N Go"],dummyobj,dummyobj,_fs,_fs,true,{true}],
[fuelshop5,["Gas pump","Mikes Gas"],dummyobj,dummyobj,_fs,_fs,true,{true}],
[fuelshop6,["Gas pump","JimBobs Fuel Station"],dummyobj,dummyobj,_fs,_fs,true,{true}],
[fuelshop7,["Gas pump","Fast Fuel"],dummyobj,dummyobj,_fs,_fs,true,{true}],
[fuelshop8,["Gas pump","Cum & Go"],dummyobj,dummyobj,_fs,_fs,true,{true}],
[fuelshop9,["Gas pump","Get Gas Fast"],dummyobj,dummyobj,_fs,_fs,true,{true}],
[shop1,["","Item Shop"],dummyobj,dummyobj,_is,_is,true,{true}],
[shop2,["","Item Shop"],dummyobj,dummyobj,_is,_is,true,{true}],
[shop3,["","Item Shop"],dummyobj,dummyobj,_is,_is,true,{true}],
[shop4,["","Item Shop"],dummyobj,dummyobj,_is,_is,true,{true}],
[pub1,["pub","Taksitan Pub"],dummyobj,dummyobj,_pub,_pub,true,{true}],
[pub2,["pub","Joeys Pub"],dummyobj,dummyobj,_pub,_pub,true,{true}],
[pub3,["pub","Lukes Pub"],dummyobj,dummyobj,_pub,_pub,true,{true}],
[gunshop1,["Rifle","Gun Shop"],gunbox1,dummyobj,_gs,_gs,true,{true}],
[checkpoint,["tools","Checkpoint Shop"],dummyobj,dummyobj,_cp,_cp,true,{true}],
[equipshop,["tools","Equipment Shop"],equipbox,dummyobj,_es,_es,true,{true}],
[equipshop4,["tools","Equipment Shop"],equipbox4,dummyobj,_es,_es,true,{true}],
[equipshop6,["tools","Equipment Shop"],equipbox6,dummyobj,_es,_es,true,{true}],
[equipshop7,["tools","Equipment Shop"],equipbox7,dummyobj,_es,_es,true,{true}],
[carshop1,["Car","Car Shop"],dummyobj,carspawn1,_cs,_cs,true,{true}],
[carshop2,["Car","Car Shop"],dummyobj,carspawn2,_cs,_cs,true,{true}],
[carshop3,["Car","Car Shop"],dummyobj,carspawn3,_cs,_cs,true,{true}],
[carshop4,["Car","Car Shop"],dummyobj,carspawn4,_cs,_cs,true,{true}],
[carshop5,["Car","Car Shop"],dummyobj,carspawn5,_cs,_cs,true,{true}],
[carshop6,["Car","Car Shop"],dummyobj,carspawn6,_cs,_cs,true,{true}],
[carshop7,["Car","Car Shop"],dummyobj,carspawn7,_cs,_cs,true,{true}],
[carshop8,["Car","Car Shop"],dummyobj,carspawn8,_cs,_cs,true,{true}],
[truckshop,["truck","Truck Shop"],dummyobj,truckspawn,_ts,_ts,true,{true}],
[truckshop2,["truck","Truck Shop"],dummyobj,truckspawn2,_ts,_ts,true,{true}],
[airshop,["heli","Air Shop"],dummyobj,asairspawn,_as,_as,true,{true}],
[airshop2,["heli","Loy Manara Air Shop"],dummyobj,asairspawn2,_as_1,_as_1,true,{true}],
[tdoc,["","Doctor"],dummyobj,dummyobj,_td,_td,true,{true}],
[Oil_1,["tools","Mining equipment"],dummyobj,dummyobj,_ms,_ms,true,{true}],
[Oil_2,["tools","Mining equipment"],dummyobj,dummyobj,_ms,_ms,true,{true}],
[resourcesell,["","Sell Resources"],dummyobj,dummyobj,_rs,_rs,true,{true}],
[resourcesell2,["","Sell Resources"],dummyobj,dummyobj,_rs,_rs,true,{true}],
[southshop1,["","General Shop"],southshopbox1,dummyobj,_generalstore,_generalstore,true,{true}],
[RingShop,["","Ring Sell"],dummyobj,dummyobj,_gds,_gds,true,{true}],
[OilSell1,["oil","Oil Dealer"],dummyobj,dummyobj,_empty,_os,true,{true}],
[gangarea1,["Rifle","Gang Shop"],gangbox1,dummyobj,_gangshop_buy,_gangshop_buy,true,{true}],
[gangarea2,["Rifle","Gang Shop"],gangbox2,dummyobj,_gangshop_buy,_gangshop_buy,true,{true}],
[gangarea3,["Rifle","Gang Shop"],gangbox3,dummyobj,_gangshop_buy,_gangshop_buy,true,{true}],
[cdrugsell,["Cocaine","Sell Cocaine"],dummyobj,dummyobj,_empty,_dsc,true,{true}],
[mdrugsell,["Marijuana","Sell Marijuana"],dummyobj,dummyobj,_empty,_dsm,true,{true}],
[ldrugsell,["Marijuana","Sell LSD"],dummyobj,dummyobj,_empty,_dsl,true,{true}],
[hdrugsell,["meth","Sell Heroin"],dummyobj,dummyobj,_empty,_dsh,true,{true}],
[Copcar,["PD","Police Vehicle Shop"],dummyobj,ccarspawn,_cv,_cv,true,{true}],
[Copair,["heli","Police Air Vehicle Shop"],dummyobj,cairspawn,_ca,_ca,true,{true}],
[swatcar,["PD","SOBR Vehicle Shop"],dummyobj,scarspawn,_sv,_sv,true,{true}],
[swatair,["heli","SOBR Air Vehicle Shop"],dummyobj,saairspawn,_sa,_sa,true,{true}],
[pmccar,["car","PMC Land Vehicle Shop"],dummyobj,pmccarspawn,_pmcveh,_pmcveh,true,{true}],
[pmcair,["heli","PMC Air Vehicle Shop"],dummyobj,pmcairspawn,_pmcair,_pmcair,true,{true}],
[Copbasic,["PD","Police Shop"],Copbasic,dummyobj,_copshop,_copshop,true,{true}],
[Coppatrol,["PD","Patrol-Officer"],Coppatrol,dummyobj,_copshop_patrol,_copshop_patrol,true,{true}],
[Copcriminal,["PD","Criminal Response-Officer"],Copcriminal,dummyobj,_copshop_response,_copshop_response,true,{true}],
[Copswat,["PD","SOBR"],Copswat,dummyobj,_copshop_sobr,_copshop_sobr,true,{true}],
[pmcbox,["","PMC Equipment"],pmcbox,dummyobj,_pmcs,_pmcs,true,{true}],
[terrorshop,["Rifle","Terrorist Shop"],tgunbox,dummyobj,_terrorshop_buy,_terrorshop_buy,true,{true}],
[vipbox,["Rifle","Illegal Weapon Shop"],vipbox,dummyobj,_smgrw,_smgrw,true,{true}],
[vipcar,["car","Stolen Vehicles"],dummyobj,vipcarspawn,_smgrveh,_smgrveh,true,{true}],
[fishmonger,["","Sell to Fishmonger"],dummyobj,dummyobj,_fm,_fm,true,{true}],
[butcher,["","Sell to Butcher"],dummyobj,dummyobj,_bm,_bm,true,{true}],
[butcher_1,["","Sell to Crazy Butcher"],dummyobj,dummyobj,_bm1,_bm1,true,{true}],
[hashbar,["","Get High"],dummyobj,dummyobj,_hash,_hash,true,{true}],
[insgunshop,["Rifle","Weapons"],insgunbox,dummyobj,_igs,_igs,true,{true}],
[inshelishop,["heli","Helicopters"],dummyobj,inshelispawn,_ihs,_ihs,true,{true}],
[inssupplyshop,["","Supplies"],dummyobj,dummyobj,_isup,_isup,true,{true}],
[insvehshop,["car","Light Vehicles"],dummyobj,insvehspawn,_bt,_bt,true,{true}],
[inshvyveh,["truck","Heavy Vehicles"],dummyobj,inshvyspawn,_ihvy,_ihvy,true,{true}],
[insairveh,["heli","Aircraft"],dummyobj,insairspawn,_iair,_iair,true,{true}],
[redgunshop,["rifle","Weapons"],redgunbox,dummyobj,_rgs,_rgs,true,{true}],
[redsupplyshop,["","Supplies"],dummyobj,dummyobj,_rsup,_rsup,true,{true}],
[redhelishop,["heli","Helicopters"],dummyobj,redhelispawn,_rhs,_rhs,true,{true}],
[redltveh,["car","Light Vehicles"],dummyobj,redvehspawn,_rlt,_rlt,true,{true}],
[redhvyveh,["truck","Heavy Vehicles"],dummyobj,redhvyspawn,_rhvy,_rhvy,true,{true}],
[redairveh,["heli","Aircraft"],dummyobj,redairspawn,_rair,_rair,true,{true}],
[airshop3,["","Armed Vehicles"],dummyobj,asairspawn3,_as_2,_as_2,true,{true}],
[fortshop1,["","Blufor Fortifications Shop"],dummyobj,fortshop1s,_fs1,_fs1,true,{true}],
[fortshop2,["","PMC Fortifications Shop"],dummyobj,fortshop2s,_fs2,_fs2,true,{true}],
[fortshop3,["","Factory Fortifications Shop"],dummyobj,fortshop3s,_fs3,_fs3,true,{true}],
[fortshop4,["","Terror Fortifications Shop"],dummyobj,fortshop4s,_fs4,_fs4,true,{true}],
[fortshop5,["","Opfor Fortifications Shop"],dummyobj,fortshop5s,_fs5,_fs5,true,{true}],
[fortshop6,["","Insurgent Fortifications Shop"],dummyobj,fortshop6s,_fs6,_fs6,true,{true}],
[vipfortshop,["","VIP Fort Shop"],dummyobj,vipfortshops,_fsvip,_fsvip,true,{true}],
[hpcar,["","Hospital Vehicle Shop"],dummyobj,hospitalspawn,_hp,_hp,true,{true}],
[hpcar_1,["","Hospital Vehicle Shop"],dummyobj,hospitalspawn_1,_hp,_hp,true,{true}],
[russmuggler,["","Russian Arms Dealer"],rusgunbox,dummyobj,_russ,_russ,true,{true}],
[mainbankShop,["","Bank Insurance"],dummyobj,dummyobj,_bank,_bank,true,{true}],
[supportercarshopciv,["car","Civ supporter Vehicle Shop"],dummyobj,civdcarspawn,_cdvs,_cdvs,true,{true}],
[supporterboxshopciv,["car","Civ supporter Weapons Shop"],supporterboxshopciv,dummyobj,_cdws,_cdws,true,{true}],
[supporterairshopciv,["heli","Civ supporter Air Shop"],dummyobj,civdairspawn,_cdas,_cdas,true,{true}],
[supportercarshopind,["car","Indep supporter Vehicle Shop"],dummyobj,inddcarspawn,_idvs,_idvs,true,{true}],
[supporterboxshopind,["Rifle","Indep supporter Weapons Shop"],supporterboxshopind,dummyobj,_idws,_idws,true,{true}],
[supporterairshopind,["heli","Indep supporter Air Shop"],dummyobj,inddairspawn,_idas,_idas,true,{true}],
[supportercarshopcop,["car","Blufor supporter Vehicle Shop"],dummyobj,copdcarspawn,_cpdvs,_cpdvs,true,{true}],
[supporterboxshopcop,["Rifle","Blufor supporter Weapons Shop"],supporterboxshopcop,dummyobj,_cpdws,_cpdws,true,{true}],
[supporterairshopcop,["heli","Blufor supporter Air Shop"],dummyobj,copdairspawn,_cpdas,_cpdas,true,{true}],
[supportercarshopopf,["car","Opfor supporter Vehicle Shop"],dummyobj,opfdcarspawn,_odvs,_odvs,true,{true}],
[supporterboxshopopf,["Rifle","Opfor supporter Weapons Shop"],supporterboxshopopf,dummyobj,_odws,_odws,true,{true}],
[supporterairshopopf,["heli","Opfor supporter Air Shop"],dummyobj,opfdairspawn,_odas,_odas,true,{true}]
];